### ISSUE TITLE
Code duplication in the expanded macro?

### ISSUE THREAD

**Issue by haxorcize** [Brendan-Blanchard/retry-if#1]
First off, amazing crate. I tried multiple other crates before finding this one, and I kept running into an incredibly complex and horrible looking API, while doing retries on my own with just a loop and sleep was so much easier, it was like these other libraries are the opposite of zero cost abstractions. So that made me wonder if there's a macro based solution and found your awesome crate.

As for my "issue": In `decorate_fn` (inside retry-if-macro/lib.rs crate) you are referencing `#block` twice. Once before the loop, and once inside the loop.

Looking at the `cargo expand` output, you can see the wrapped function's entire code being produced twice. And I assume the compiler can optimize it away but it would be cleaner to change the structure of the loop so that the evaluations happen inside the loop, and thus `#block` would be reference only once.

WDYT?

**Comment by Brendan-Blanchard** [comment]
Hey! Thanks for filing an issue, and I'm glad you like the semantics. I was very much going after a Python-like decorator after also surveying what was out there and not finding one I liked.

The initial justification for the double-expansion is that there needs to be a guaranteed value to return from the function, since the loop could execute zero times if the backoff is misconfigured. I tried a few ways to encapsulate the expanded code like `let call = || #block` and using `call().await` instead of the second expansion, but you run into issues with async closures support, or ownership of anything inside it with async blocks unless I'm missing something. 

It looks like an option (and expect/panic if mis-configured) is the best path forward? I've made those changes in https://github.com/Brendan-Blanchard/retry-if/pull/2 which shows an example of the expansion without duplication. Can you pull it and see if it introduces anything unexpected for your use-case? I'll also be testing it with my own usages a little more before feeling confident in the change.

**Comment by haxorcize** [comment]
Thanks for the speedy response. Code looks great. 

Btw what do you think of the following as a way to remove the `Option<_>` and also ensure there's at least one run, thus keeping the name `max_retries`, by switching to a `loop {..}`:

```rust
fn decorate_fn(impl_fn: ItemFn, config: &Ident, retry_if: &Ident) -> proc_macro::TokenStream {
    let attrs = &impl_fn.attrs;
    let vis = &impl_fn.vis;
    let sig = &impl_fn.sig;
    let block = &impl_fn.block;

    (quote! {
        #(#attrs)*
        #vis #sig {
            let start = tokio::time::Instant::now();
            let backoff_max = #config.backoff_max.unwrap_or(std::time::Duration::MAX);
            let mut attempt = 0;

            loop {
                let result = #block;

                // Return result if retry isn't required, or if we ran out of attempts
                if !#retry_if(&result) || attempt >= #config.max_retries {
                    return result;
                }
                attempt += 1;

                let retry_wait = #config.t_wait
                    .mul_f64(#config.backoff.powi(attempt))
                    .min(backoff_max);

                if let Some(max_wait) = #config.t_wait_max {
                    let now = tokio::time::Instant::now();
                    let since_start = now - start;

                    // Return if our overall duration is going to exceed `max_wait`
                    if since_start + retry_wait > max_wait {
                        return result;
                    }
                }

                if cfg!(feature = "tracing") {
                    tracing::info!("Sleeping {retry_wait:?} on attempt {attempt}");
                }
                tokio::time::sleep(retry_wait).await;
            }
        }
    })
        .into()
}
```

(Also happy to comment on the PR if you prefer)

**Comment by Brendan-Blanchard** [comment]
This is nicer than the Option.take route, I'm happy to include this as part whatever we decide for the larger issue with early returns and the try operator.
